spring:
  application:
    name: patient-services      
server.port: 4444
---
spring:
  profiles: prod
  datasource:
    url: jdbc:h2:mem:prodDb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

spring.data.jpa.repositories.bootstrap-mode: default


---


spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testDB
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

spring.data.jpa.repositories.bootstrap-mode: default