spring:
  application:
    name: patient-services      
server.port: 4444

feign.client.config.default.connectTimeout: 5000
feign.client.config.default.readTimeout: 5000
---
spring:
  profiles: prod
  datasource:
    url: jdbc:h2:mem:prodDb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

spring.data.jpa.repositories.bootstrap-mode: default
external-user-url: https://jsonplaceholder.typicode.com/

---


spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testDB
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

spring.data.jpa.repositories.bootstrap-mode: default
external-user-url: http://localhost:3434/
